### ISSUE TITLE
extend readme

### ISSUE THREAD

**Issue by altayaydemir** [barbar/vortigern#10]

**Comment by batuhan** [comment]
About the readme, I think these titles would be just enough:

- Packages we use (and why we use them for the ones that are not instantly obvious)
- Installation and usage (ofc.)
- People who helped making this (it's just a short list with @altayaydemir's name in it. We should't call this "Maintainers" 'cause of the next point)
- A note that says we give no promises to maintain this starter
- Explanation for the directory structure 


Also, I don't think we need the note about the typings, anyone who writes TypeScript should be aware of that, no?

**Comment by altayaydemir** [comment]
I agree all of them, we should also note that Typescript that we wrote here is not the "most appropriate" way to use with React. However, we can (actually, we must) keep the codebase up-to-date as we become familiar with ts & react duo.
