### ISSUE TITLE
Default installation cannot run tests

### ISSUE THREAD

**Issue by liukun** [barbar/vortigern#102]
According to https://github.com/facebook/react/issues/8314

    react-addons-test-utils
    react
    react-dom

These modules should use same version for now. However, in current package.json

    "react-addons-test-utils": "^15.3.2",
    "react": "~15.3.2",
    "react-dom": "~15.3.2",

which installs
```
├── react@15.3.2
├── react-addons-test-utils@15.4.1
├── UNMET PEER DEPENDENCY react-dom@15.3.2
```
then `npm test` gives
```
ERROR in ./~/react-addons-test-utils/index.js
Module not found: Error: Cannot resolve module 'react-dom/lib/ReactTestUtils' in /Volumes/SSD2012/Work/vortigern/node_modules/react-addons-test-utils
 @ ./~/react-addons-test-utils/index.js 1:17-56
npm ERR! Test failed.  See above for more details.
```
Change package.json to 

    "react-addons-test-utils": "~15.3.2",
Fixed the tests.

**Comment by altayaydemir** [comment]
hello, thanks for the feedback!

if its fixed your issue, would you like to open a pr for this? 😊

**Comment by liukun** [comment]
Sure, PR created.
