### ISSUE TITLE
a-question about path 

### ISSUE THREAD

**Issue by ynanzero** [barbar/vortigern#112]
import { App, Home, About, Counter, Stars } from 'containers';

how did you do that? where is config?

**Comment by altayaydemir** [comment]
https://github.com/barbar/vortigern/blob/develop/tsconfig.json#L4-L9

**Comment by ynanzero** [comment]
thanks , I alreay figured it out.
but i think you should write in README.md 
in my computer(windows) vscode is not that smart
it will show you red line
