### ISSUE TITLE
React attempted to reuse markup in a container but the checksum was invalid.

### ISSUE THREAD

**Issue by matb** [barbar/vortigern#113]
I just cloned the latest version and when running the app I get two errors: 

1: During the load, this warning is thrown in the console:

`React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ass="appContainer___1pMKz" data-reactroo
 (server) ass="appContainer___385DV" data-reactroo`

2: On page refresh the page is first loaded without styles and afterwards they are applied. This makes the page look pretty ugly during the load. I checked in Postman and I can confirm, that no styles are present during the first load. 

Is there any fix for this?

**Comment by altayaydemir** [comment]
Please refer to https://github.com/barbar/vortigern/issues/76 and https://github.com/barbar/vortigern/issues/59

**Comment by dmitry-korolev** [comment]
Actually the first problem described in @matb issue does exist. It can be reproduced on fresh vortigem install.
Steps to reproduce:
1. Install vortigem as described in the Installation section of README.md
2. Fix lint error in vendor/main.ts ;)
3. Run `npm start`
4. Open new tab, open devtools, navigate to http://localhost:8889/

Expected:
No errors in the console

Actual:
Error:
![image](https://cloud.githubusercontent.com/assets/12699282/22502614/b4a88046-e87e-11e6-9ed7-3cbf3b8b292c.png)

BTW, notice same class names on the client and different class names on the server side at my case and at @matb case.

**Comment by altayaydemir** [comment]
@dmitry-korolev thanks for the explanation. 

Since I'm not using vortigern in my daytime job, I'm unable to spot these kind problems. However, I will check it out during the weekend.

If you find a solution, please don't hesitate to open a PR 👍

**Comment by dmitry-korolev** [comment]
@altayaydemir obvioisly, there is some difference in the context, passed to hash function.
I used getLocalIdent (css-loader option, available in webpack 2) to bypass that problem, but that's just a workaround, not suitable for production, I guess.

**Comment by matb** [comment]
@dmitry-korolev Does the issue also appear in the production build? I currently have the impression that it only happens in the development build.

**Comment by dmitry-korolev** [comment]
@matb 
It doesn't show any warnings in the console (because it's, well, production mode), but yes, server-rendered markup differs from client-side render in a same way.
