### ISSUE TITLE
Generate static index.html on build

### ISSUE THREAD

**Issue by matthiasleitner** [barbar/vortigern#115]
Hi,

is it somehow possible to write a index.html to disk on production builds so the app can be served without server-side rendering?

What would be the best approach to achieve this when contributing?

Thanks!

**Comment by altaywtf** [comment]
Hi @matthiasleitner, unfortunately we've only focused on server-side rendering on vortigern. Preparing a client side version in a separate branch was one of our ideas for v2 but no proper attempts made so far 😅 .

However, [I have a toy project written with typescript-react-redux stack](https://github.com/LaborWorks/bilgi-shuttle-web) which renders on the client side. Dependencies are a little bit outdated but if you're looking for an easy solution you can check it out. If you're willing to contribute vortigern, maybe you can start with extracting server side code and build configuration.
