### ISSUE TITLE
Compatibility between react-router and history

### ISSUE THREAD

**Issue by paibamboo** [barbar/vortigern#116]
Hi, react-router 3.0.2 is compatible with history ^3.0.0, may I ask why history 4.5.1 is being used? 

![react_router_dependencies](https://cloud.githubusercontent.com/assets/13611391/22819633/9114a91a-efa5-11e6-8b77-7da28aa67e30.png)

I'm asking because this breaks the compilation of the test using [karma-typescript](https://github.com/monounity/karma-typescript)

**Comment by patroza** [comment]
Habbit to update to the latest, however it seems 4.5.1 is not fully compatible with react-router.
It would be better to downgrade history and the related types dependency.

**Comment by altaywtf** [comment]
fixed in https://github.com/barbar/vortigern/commit/16fe9a85d848ccb9356510c45c6c86342775d686
