### ISSUE TITLE
npm start not running

### ISSUE THREAD

**Issue by lukephills** [barbar/vortigern#118]
Hi, I just tried a fresh install and npm start and these errors come up
```
ERROR in [at-loader] node_modules/@types/react-router-redux/index.d.ts:9:10 
    TS2305: Module '"/Users/luke/Downloads/barbar-vortigern-0be1328/node_modules/@types/react-router/index"' has no exported member 'Location'.

ERROR in [at-loader] src/server.tsx:57:40 
    TS2345: Argument of type 'History.History' is not assignable to parameter of type 'History'.
  Property 'length' is missing in type 'History'.
```

Do I have the wrong type versions perhaps?

**Comment by lukephills** [comment]
Yeah @types/react-router and react router dependencies should be "^3.0.2"

**Comment by Aristona** [comment]
I also got the same error and this is the fix. Perhabs you should make a PR @lukephills ?

**Comment by altaywtf** [comment]
fixed in https://github.com/barbar/vortigern/commit/16fe9a85d848ccb9356510c45c6c86342775d686, thanks guys.
