### ISSUE TITLE
LESS styles

### ISSUE THREAD

**Issue by alexhumanbean** [barbar/vortigern#125]
Hi, I'm trying to use LESS styles. Configuration in dev.js looks good (I use good configuration from another project), but less-loader is not working yet:
 
ERROR in ./src/app/containers/App/style.less
Module parse failed: c:\work\spa\src\app\containers\App\style.less Unexpected to ken (1:0)
You may need an appropriate loader to handle this file type.
| .AppContainer {
|   padding: 0;
|   margin: 0;
 @ ./src/app/containers/App/index.tsx 16:12-35
 @ ./src/app/containers/index.tsx
 @ ./src/server.tsx

I see you use postcss, but have you tried to use LESS or SASS in this boilerplate?

**Comment by altaywtf** [comment]
@alexhumanbean no, we haven't tryied to implement scss or less to vortigern and I guess its not in our plans. However, I'd like to help you about this if you post your webpack configuration.

**Comment by alexhumanbean** [comment]
We have managed to implement less to Vortigern. Thank you!
