### ISSUE TITLE
Importing CSS (and other assets) from NPM packages

### ISSUE THREAD

**Issue by jonlambert** [barbar/vortigern#127]
Hey! 
What is the correct way to include and handle CSS/fonts resources from NPM packages?

**Comment by altaywtf** [comment]
Hi, you can check this file: https://github.com/barbar/vortigern/blob/master/src/vendor/main.ts and https://github.com/postcss/postcss-import

**Comment by jonlambert** [comment]
Hi @altayaydemir, thanks for your reply! I've tried importing CSS files within `main.ts`, but I'm not entirely sure where these can be used?
