### ISSUE TITLE
that is A problem in Build 

### ISSUE THREAD

**Issue by karangoswami31** [barbar/vortigern#133]
D:\Karan\Learn\React\vortigern>npm start or npm run build:prod  

> vortigern@0.1.2 prestart D:\Karan\Learn\React\vortigern
> npm run build

> vortigern@0.1.2 prebuild D:\Karan\Learn\React\vortigern
> npm run clean

> vortigern@0.1.2 clean D:\Karan\Learn\React\vortigern
> rimraf build

D:\Karan\Learn\React\vortigern\node_modules\rimraf\bin.js:47
      throw er
      ^

Error: EBUSY: resource busy or locked, rmdir 'D:\Karan\Learn\React\vortigern\build'
    at Error (native)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\node\\node.exe" "C:\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vortigern@0.1.2 clean: `rimraf build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vortigern@0.1.2 clean script 'rimraf build'.

**Comment by bherila** [comment]
Did you try running it again? I have seen this problem intermittently on Windows. I don't think it's related to Vortigern itself.

**Comment by altaywtf** [comment]
@karangoswami31 please provide more info, I'm closing this one for now.
