### ISSUE TITLE
Choose which routes should use server side rendering

### ISSUE THREAD

**Issue by johnnyvf24** [barbar/vortigern#136]
Loving the starter kit, but unfortunately, some of the libraries I am using aren't compatible with Server Side Rendering. How would I go about only doing client-side rendering for specific routes?

**Comment by ufukomer** [comment]
https://github.com/barbar/vortigern/issues/126#issuecomment-287743433

**Comment by johnnyvf24** [comment]
I am not looking to completely eliminate server-side rendering but only do so for a specific route.

**Comment by bherila** [comment]
@johnnyvf24 does this help?

```tsx
export class ClientComponentContainer extends React.Component<any, any> {
	constructor(props, context) {
		super(props, context)
		this.state = {isLoaded: false};
	}

	public render() {
		if (!isLoaded) return <div>Loading</div>;
		/* put your code here that should only be rendered client side */
	}

	public componentDidMount() {
		/* this is only run client-side */
		this.setState({isLoaded: true});
	}
}
```

**Comment by altaywtf** [comment]
@bherila this is a good suggestion!
