### ISSUE TITLE
CSS file extension?

### ISSUE THREAD

**Issue by bherila** [barbar/vortigern#137]
Loving the next-gen css features from https://github.com/barbar/vortigern/issues/48 but should we consider renaming the files to .scss to increase compatibility with editors?

![image](https://user-images.githubusercontent.com/1422004/27407551-97f9c338-568d-11e7-92e9-27099d1bcad7.png)

**Comment by altaywtf** [comment]
you are damn right, but they're not scss :-/

**Comment by bherila** [comment]
What are they @altayaydemir ?

When I rename the files to .scss, the errors go away but the loading doesn't work anymore :-\

**Comment by altaywtf** [comment]
They're css-next 😃 

If you want to convince your editor by renaming them as css and also make vortigern work, I guess you can update

* https://github.com/barbar/vortigern/blob/develop/config/webpack/dev.js#L53
* https://github.com/barbar/vortigern/blob/develop/config/webpack/prod.js#L59

as `test: /\.scss$/`.

or you can remove all css-next related things and just use the real scss with sass loader and etc 😅
