### ISSUE TITLE
Where is vendor.css supposed to come from?

### ISSUE THREAD

**Issue by bherila** [barbar/vortigern#145]
There is a call to resolve a file called vendor.css but it is not clear where this file is supposed to come from. Should this be generated in webpack somehow?

```js
const styles = this.resolve(['vendor.css', 'app.css']);
```

Thanks,
Ben

**Comment by TriStarGod** [comment]
I also searched for the vendor.css. Maybe it doesn't include it if its not resolved?

**Comment by bherila** [comment]
That's right, it doesn't include it because it's not resolved. My question is, how *should* it be generated (i.e. from the vendor folder somehow)?

**Comment by ufukomer** [comment]
@bherila Try to uncomment this: https://github.com/barbar/vortigern/blob/develop/src/vendor/main.ts#L4
