### ISSUE TITLE
webpack-hot-middleware-clientOverlay giving vague errors

### ISSUE THREAD

**Issue by TriStarGod** [barbar/vortigern#146]
If I make a mistake like not putting a newline after each line of code or a space before the start of comment, it gives me a vague error "Module build failed: Error: Compilation failed due to tslint errors."

How do I get it to display the error that "npm run lint" displays?

Also, how can I disable some of these pointless errors?

**Comment by bherila** [comment]
Scroll up above the webpack build, the errors are written in the terminal to stdout.

You can edit the tslint config file (in the root dir) to add/change/remove rules to your liking.

**Comment by TriStarGod** [comment]
The errors do show up when you first run it in the terminal. However, after its continuously running, no errors are outputted in the terminal.

**Comment by bherila** [comment]
Hmm you're right. I'm not sure how to fix it though :(

Luckily I am using an editor (PHPStorm) which provides built in tslint support, and so the errors just end up as red squiggles. I think VS Code may provide a similar level of support as well.

**Comment by TriStarGod** [comment]
Thank youuuuuu @bherila . That lead me my alternative, vscode's tslint extension.
