### ISSUE TITLE
Request: upgrade to typescript 2.4 support

### ISSUE THREAD

**Issue by bherila** [barbar/vortigern#147]
There are a bunch of breaking changes with the react typings etc. which has proven to be a challenge for me upgrading to typescript 2.4 with this starter pack. Is there any plan to upgrade the template to support the latest typings, react router v4, etc.?

Happy to start a branch and send PRs or work off a branch/fork, but I'm only keen to start this if there is  someone out there who can help me if/when I run into issues :)

**Comment by foklepoint** [comment]
I'm hitting this pain point. I would love for this to be updated to support the new react router, upgraded version of typescript.

**Comment by altaywtf** [comment]
thanks to @psrebniak!
