### ISSUE TITLE
CSS sourcemap is missing in dev.config?

### ISSUE THREAD

**Issue by ayavryk** [barbar/vortigern#153]
CSS sourcemap is missing in dev.config?

**Comment by ayavryk** [comment]
I updated the version of css-loader from 0.26.1 to 0.26.4
and  updated  webpack loaders line 
from
'css-loader?modules&importLoaders=2&localIdentName=[local]___[hash:base64:5]',
to
'css-loader?sourceMap&modules&importLoaders=2&localIdentName=[local]___[hash:base64:5]',



Sourcemap  has appeared

**Comment by altaywtf** [comment]
@ayavryk great! PRs are welcomed 😉
