### ISSUE TITLE
support Electron (or not?)

### ISSUE THREAD

**Issue by batuhan** [barbar/vortigern#30]
I'll convert [barbar/riothamus](https://github.com/barbar/riothamus) to TypeScript and couldn't decide if I should push the Electron-specific edits back to Vortigern or fork Vortigern to create another boilerplate for Electron.

Any ideas?

**Comment by batuhan** [comment]
Keep in mind that some parts of the Vortigern like the isomorphic render are not needed in an Electron project. With that in mind, I think best course is to forking and simplifying Vortigern.

**Comment by altayaydemir** [comment]
As you said, we can do it in a separate repo. It would be great to have similar configurations and structure. I was also considering to prepare a simplified, only client-side rendered version of vortigern for smaller (or toy) projects.

**Comment by batuhan** [comment]
It's settled then. I'll merge the PR I have opened here, after that I'll start working on this.
