### ISSUE TITLE
npm start / npm run start fails due to NODE_ENV not found

### ISSUE THREAD

**Issue by RaphaelHippe** [barbar/vortigern#39]
Hello, 
I wanted to give vortgern a try and did the following: 
```bash
$ git clone https://github.com/barbar/vortigern
$ cd vortigern
$ npm run setup
```
everything worked so far. 

Now I am getting an error when trying to start it: 
```bash
$ npm start
```
Here is a screenshot of the console output:
![image](https://cloud.githubusercontent.com/assets/9699496/15702351/ea0ee3de-27df-11e6-9cdc-b534080973ca.png)

I am using windows 10. 
My node version is V4.4.3
My npm version is 3.8.2

I couldn't find anything on google regarding my issue. I hope you can help me. Thanks!

Cheers,
Raphael Hippe

**Comment by batuhan** [comment]
Hey Raphael, 

Can you try running `NODE_ENV=development npm start` while I check why it didn't falled back to the default parameters?

Thanks.

**Comment by batuhan** [comment]
Hey Raphael, 

Sorry for the inconvenience, I've just checked our start scripts and it appears it's related to Windows and how it handles setting environmental variables. I'll check on how to fix that and get back to you.

Thanks.

**Comment by ilgooz** [comment]
hi @RaphaelHippe, you can easily fix this by changing the way how env variables set in _package.json_ and _Makefile_ for Windows.

e.g.

this:
`ENV1=value1 ENV2=value2 make build` 
becomes to:
`SET ENV1=value1 && SET  ENV2=value2 && make build`

**Comment by RaphaelHippe** [comment]
Hey, 

thanks for the very quick answers. 
This worked as in it brought up new errors for me. 
First I had to install make for windows (msysgit) to execute the make files. 

now using the $ npm start command I am getting a ton of WARNINGS and ERRORS. 
I am gonna attach some screenshots again. 

### Warnings

![image](https://cloud.githubusercontent.com/assets/9699496/15736843/ce9122e8-28a2-11e6-9f0b-8cba04772243.png)

### Errors

![image](https://cloud.githubusercontent.com/assets/9699496/15736859/de89d582-28a2-11e6-9e0f-9a5ff2baaf66.png)

![image](https://cloud.githubusercontent.com/assets/9699496/15736875/eedc4294-28a2-11e6-825f-b2b675c74f28.png)

### NPM Debug Log

[npm-debug-log.txt](https://github.com/barbar/vortigern/files/295043/npm-debug-log.txt)

Thanks again, looking forward to hearing from you again. 

Cheers

**Comment by altayaydemir** [comment]
@RaphaelHippe 

Hi, I've made a change which seems related to solution of your problem. Can you try with the latest version?

**Comment by RaphaelHippe** [comment]
Hey, 

your fix got rid of some Errors and all the Warnings. 
Although the Errors with the CSS modules still remain. (previous provided screenshots)

Thanks

**Comment by altayaydemir** [comment]
@RaphaelHippe 

Happy to hear that :) 

I was suspecting the NPM version (btw we all run the latest version: 6.2) but I tried to run vortigern with a fresh install on npm 4.4.4 and it was working as expected.

We will keep investigating the crux. In the meantime, please don't hesitate to ping us (or open a pull request) if you come up with an idea (or a solution!).

**Comment by omencat** [comment]
Hi,

Having a similar issue on Windows dev box, though I skipped the whole makefile portion and just ran the webpack commands manually for now.

both webpack commands appear to return without error:

```
 PS C:\Users\Joe\Documents\GitHub\vortigern> webpack --config .\config\webpack\dev.js
ts-loader: Using typescript@1.8.10 and C:\Users\Joe\Documents\GitHub\vortigern\tsconfig.json
Hash: 4fc16894fcceff0bd9b3
Version: webpack 1.13.1
Time: 3915ms
                                      Asset      Size  Chunks             Chunk Names
images/a6a8103e977275e28df8224ed8d6521e.png   16.7 kB          [emitted]
                                  js/app.js   1.25 MB       0  [emitted]  app
                           ../manifest.json  98 bytes          [emitted]
   [0] multi app 40 bytes {0} [built]
 [277] ./config/main.js 702 bytes {0} [built]
    + 313 hidden modules
PS C:\Users\Joe\Documents\GitHub\vortigern> webpack --config .\config\webpack\server.js
ts-loader: Using typescript@1.8.10 and C:\Users\Joe\Documents\GitHub\vortigern\tsconfig.json
Hash: ac874fe61cac7dd45ea6
Version: webpack 1.13.1
Time: 3292ms
                                      Asset     Size  Chunks             Chunk Names
images/a6a8103e977275e28df8224ed8d6521e.png  16.7 kB          [emitted]
                               ../server.js   680 kB       0  [emitted]  main
   [1] ./config/main.js 702 bytes {0} [built]
 [203] ./config/webpack/dev.js 2.68 kB {0} [built]
    + 210 hidden modules
PS C:\Users\Joe\Documents\GitHub\vortigern>
```

when i run the build/server.js though I get window is not defined. Googling around seems to indicate something about there not being a window object when targeting node / when server-side rendering.

```
PS C:\Users\Joe\Documents\GitHub\vortigern> node .\build\server.js
C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:19417
                        return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
                                                   ^

ReferenceError: window is not defined
    at C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:19417:31
    at C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:19412:48
    at module.exports (C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:19434:69)
    at Object.<anonymous> (C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:19727:39)
    at __webpack_require__ (C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:21:30)
    at Object.<anonymous> (C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:19703:10)
    at __webpack_require__ (C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:21:30)
    at Object.<anonymous> (C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:19171:15)
    at __webpack_require__ (C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:21:30)
    at Object.<anonymous> (C:\Users\Joe\Documents\GitHub\vortigern\build\server.js:19156:21)
```

**Comment by batuhan** [comment]
Just wanted to give you guys an update. @ufukomer is currently working on the Windows bugs. We've also setup a Windows VM for testing so we expect less problems with Windows in the future.

Thanks for trying out Vortigern.

**Comment by RaphaelHippe** [comment]
Hey guys, 
just wanted to let you know your changes worked for me!
Thanks for the support :)

**Comment by batuhan** [comment]
That's perfect news @RaphaelHippe.

Please let us know any feedbacks you may have so we can make Vortigern better. :)

**Comment by omencat** [comment]
Glad I checked back. Did a fresh install and it works like a charm on Windows 10. Great job guys.
