### ISSUE TITLE
Can I use Vortigern without the server

### ISSUE THREAD

**Issue by casoetan** [barbar/vortigern#54]
Hi @altayaydemir, can I take out the server part of things and use this without requiring express.js. If possible please how.

**Comment by batuhan** [comment]
This is in the pipeline and we actually have an internal fork of Vortigern with optional server side rendering. IIRC, @altayaydemir has something more "finished" for this tho. Altay?

**Comment by altayaydemir** [comment]
Hello, @casoetan.

I'm using a setup which is similar to Vortigern (without server-side rendering) here: https://github.com/bilgishuttle/bilgi-shuttle-web/tree/develop it uses express only for development server. You can clone it and remove the extra work.

However, as @batuhan said we are working on a non-isomorphic version of Vortigern too.

**Comment by casoetan** [comment]
Ok. Any ETAs? I kind of like your philosophy on this + the quick responses :)

**Comment by batuhan** [comment]
Well, we could work on it and merge changes sometime next week. :)

**Comment by casoetan** [comment]
that will be great. Look forward to next week then.
