### ISSUE TITLE
npm start failed under windows

### ISSUE THREAD

**Issue by PavelTrushkin** [barbar/vortigern#63]
under pure windows w/o cygwin installed npm start is failed in package.json->scripts->clean, there is "clean": "rm -rf build/"

**Comment by altayaydemir** [comment]
Hey @PavelTrushkin, I've updated our package.json to use ```rimraf``` instead of ```rm -rf build```. can you try again?

**Comment by altayaydemir** [comment]
@PavelTrushkin any updates on this?

**Comment by PavelTrushkin** [comment]
sorry for delay yes it works for me, thank you!
