### ISSUE TITLE
nested css classes disappear after running npm run build:prod

### ISSUE THREAD

**Issue by leonzinger** [barbar/vortigern#71]
I use nested classes in some of my css files like this:

`.foo {
  & .nested {}
}`

and in the tsx file i use it like this:

`const s = require('./style.css');

div className={s.nested}
`

it runs smoothly in dev mode, but all of these classes disappear from the css after the build

**Comment by ericwooley** [comment]
It's the extract text plugin. I don't know why thats happening. But removing it fixed the problem.

Bummer though because thats a helpful thing to have.

I would investigate further, but I am doing a  cordova app, have 0 extra time, and it doesn't affect me. Good luck!

**Comment by leonzinger** [comment]
Thanks for the heads up!

**Comment by sickboy** [comment]
This issue is fixed in this pull: https://github.com/barbar/vortigern/pull/107

**Comment by altayaydemir** [comment]
hey @leonzinger @ericwooley can you guys try the latest version? @sickboy did a great job with updating the dependencies and some config. It seems like fixed to me?
