### ISSUE TITLE
TypeScript all the things?

### ISSUE THREAD

**Issue by mohsen1** [barbar/vortigern#74]
This is a suggestion. I was able to use TypeScript for webpack config and server side code and I think this project should do it too!

Take a look at my project:

https://github.com/rah-foundation/website

**Comment by altayaydemir** [comment]
we want to avoid must-have dependencies like ts-node as much as we can. our primary aim to use typescript on this boilerplate is to provide typesafety to our codebase.

thanks for your suggestion 👍
