### ISSUE TITLE
Error building on first try

### ISSUE THREAD

**Issue by YashYash** [barbar/vortigern#78]
I just cloned the repo. I ran npm install and it installed all the dependencies successfully. However when I ran npm start, it throws the following error:

-- /build/server.js:70 --
var manifest = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"../build/manifest.json\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
Error: Cannot find module "../build/manifest.json"

It looks like the manifest.json file isn't being created in the build folder.

Do you guys think I might I messed up while cloning, or missed a step?

Thanks.

**Comment by altayaydemir** [comment]
Did you solved this?

If not, can you provide some information about your development environment (like operating system and node version) please?
