### ISSUE TITLE
Tests fail, can you help to fix?

### ISSUE THREAD

**Issue by TimSusa** [barbar/vortigern#81]
npm run test

> vortigern@0.1.0 test /Users/tsusa/examples/ts-react-example
> karma start config/test/karma.conf.js

ts-loader: Using typescript@1.8.10 and /Users/tsusa/examples/ts-react-example/tsconfig.json
22 09 2016 17:33:47.288:WARN [karma]: No captured browser, open http://localhost:9876/
22 09 2016 17:33:47.298:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
22 09 2016 17:33:47.303:INFO [launcher]: Starting browser PhantomJS
22 09 2016 17:33:47.316:INFO [launcher]: Starting browser Chrome
22 09 2016 17:33:48.596:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#PrZ2xS2haYG6jCElAAAA with id 45054998
22 09 2016 17:33:48.607:INFO [Chrome 53.0.2785 (Mac OS X 10.11.6)]: Connected on socket /#j8goND23MIgaQvzAAAAB with id 39886717

START:
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: Object is not a constructor (evaluating 'configureStore(middlewares)')
  at /Users/tsusa/examples/ts-react-example/config/webpack/test.js:10212
Chrome 53.0.2785 (Mac OS X 10.11.6) ERROR
  Uncaught TypeError: configureStore is not a function
  at /Users/tsusa/examples/ts-react-example/config/webpack/test.js:10212

Finished in 0.848 secs / 0 secs

SUMMARY:
✔ 0 tests completed

**Comment by wmathes** [comment]
redux-mock-store changed something with the 1.2.x release. Pinning it back to ~1.1.0 worked for me, though i haven't investigated any further yet.

**Comment by TimSusa** [comment]
Yes, indeed. This fixed the test here. Thanks a lot!
