### ISSUE TITLE
Cannot find module "../build/manifest.json"

### ISSUE THREAD

**Issue by ttbarnes** [barbar/vortigern#97]
Hey, this starter looks great, but I can't run it from a fresh install.

I followed the steps:
```
git clone
npm install
npm start
```

I get the following error, just like in #78 

```
/Users/tonyb/_projects/vortigern/build/server.js:70
	var manifest = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"../build/manifest.json\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
	                                                                                                                                                                        ^

Error: Cannot find module "../build/manifest.json"
    at webpackMissingModule (/Users/tonyb/_projects/vortigern/build/server.js:70:81)
    at Object.module.exports.config.env (/Users/tonyb/_projects/vortigern/build/server.js:70:180)
    at __webpack_require__ (/Users/tonyb/_projects/vortigern/build/server.js:21:30)
    at module.exports.Object.assign.i (/Users/tonyb/_projects/vortigern/build/server.js:41:18)
    at Object.<anonymous> (/Users/tonyb/_projects/vortigern/build/server.js:44:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

My node version is 6.8.1, mac OS X El Capitan, 10.11.6.

**Comment by KirioXX** [comment]
Have the same problem on ubuntu 16.04, node version 7.0.0, npm version 3.10.8 .

**Comment by sethx** [comment]
Same here.
OSX Sierra 
node 7.1.0
npm 7.4.2

**Comment by arnarp** [comment]
I think the problem is a new version of React that removes ReactMount.js from its lib folder. Does the problem persist if you downgrade react to "react": "15.3.2"?

At least there seems to be some issue with that now that has to be solved by upgrade'ing react-hot-loader.

**Comment by KirioXX** [comment]
I downgrade react to 15.3.2 and everything seems to work fine.

**Comment by DonaldWebb** [comment]
Win 10, node 6.2.0, npm 3.10.6

Downgrading to "react": "15.3.2" worked, it required setting the version of the following dependencies as well.
"react-addons-test-utils": "~15.3.2",    
    "react-dom": "15.3.2"

However using the existing clone I could successfully run build:prod with react 15.4.0.
It does seem to be the hot-loader, possibly:
https://github.com/gaearon/react-hot-loader/blob/master/docs/README.md#usage-with-external-react

**Comment by ufukomer** [comment]
Try and reopen if it's not fixed for you (remove `node-modules` directory before reinstalling it).

**Comment by ufukomer** [comment]
Try and I'll reopen the issue if it's not fixed for you (remove node-modules directory before reinstalling it).

**Comment by ttbarnes** [comment]
Thanks all, working fine with react 15.3.2.

**Comment by 2225025616** [comment]
You can try install "uglifyes-webpack-plugin". I also came across this problem. That i tried update something or lowered version is invalid.
