### ISSUE TITLE
postcss-loader not emitting auto-prefixed styles

### ISSUE THREAD

**Issue by arnarp** [barbar/vortigern#98]
If I for example add flex to .home in Home/style.css 
`.home {
  text-align: center;
  display: flex;
}
`
then run `npm run start:prod`

then the css build output build/public/css/app
will be
`.nav___2ez-D ul{list-style-type:none;padding:0}.nav___2ez-D ul li{display:inline;padding:5px;color:blue}a{color:pink}.appContainer___1khLq{padding:0;margin:0;text-align:center}.home___1UsE1{text-align:center;display:flex}
`
and note that `.home___1UsE1{text-align:center;display:flex}` lacks vendor prefixes.

This problem seems to be more general. For example if I add css variable then the css output is not valid for IE, Edge

**Comment by sickboy** [comment]
postcss-loader wasn't functioning in production, that's solved with https://github.com/barbar/vortigern/pull/107 - hopefully addressing this issue too :)

**Comment by altayaydemir** [comment]
hey @arnarp can you try the latest version? @sickboy did a great job with updating the dependencies and some config.
